### ISSUE TITLE
ForwardDiff compatibility

### ISSUE THREAD

**Issue by gdalle** [gdalle/ImplicitDifferentiation.jl#1]
At the moment, autodiff of implicit functions relies on ChainRules, which means ForwardDiff won't work.

Suggested fix: manually overload the callable on ForwardDiff.Dual

**Comment by mohamed82008** [comment]
Now that https://github.com/ThummeTo/ForwardDiffChainRules.jl is a thing we can close this?

**Comment by gdalle** [comment]
Should we add it to our package?

**Comment by mohamed82008** [comment]
Or just document its use.

**Comment by mohamed82008** [comment]
Well it all depends on how light you want this package to be. But taking 1 more dep might not be the end of the world here.

**Comment by gdalle** [comment]
Not sure how to use this stuff but happy to review a PR adding this and ForwardDiff as dependencies

**Comment by rveltz** [comment]
I am interested in a simple example of use with ForwardDiff!

**Comment by mohamed82008** [comment]
See https://github.com/ThummeTo/ForwardDiffChainRules.jl/pull/11

**Comment by gdalle** [comment]
Side note: with Julia 1.9 we can add conditional dependencies

**Comment by mohamed82008** [comment]
@rveltz I will leave documenting an example to you once that PR is merged :)
