### ISSUE TITLE
sparsity gets lost: sparse array input -> dense array output

### ISSUE THREAD

**Issue by thorek1** [gdalle/ImplicitDifferentiation.jl#118]
it would be good to preserve sparsity. 
the culprit in the ForwardDiff extension is:
```julia
y_and_dy = map(eachindex(IndexCartesian(), y)) do i
    Dual{T}(y[i], Partials(ntuple(k -> dy[k][i], Val(N))))
end
```
which always creates a dense array

**Comment by gdalle** [comment]
I agree it would be good, but see #21, sparse arrays already have some problems with ForwardDiff.jl that cannot be solved

**Comment by gdalle** [comment]
The latest version no longer supports matrices, only vectors. If you want sparsity, you need to create the sparse matrix inside the function. Enzyme takes a similar approach, and it avoids lots of headaches
https://discourse.julialang.org/t/how-do-you-speed-up-the-linear-sparse-solver-in-zygote/111801/27?u=gdalle
