### ISSUE TITLE
Prevent multiple calls to `forward` when using `ForwardDiff.jacobian`

### ISSUE THREAD

**Issue by sfalmo** [gdalle/ImplicitDifferentiation.jl#131]
When calculating sufficiently large Jacobians with ForwardDiff, the `forward` mapping $x \rightarrow y(x)$ is called over and over again for each chunk that `ForwardDiff.jacobian` computes.
Here is a minimal example:

```julia
using ImplicitDifferentiation, ForwardDiff

x = rand(100)  # length(x) must be larger than the chunk size to see the effect

function sqrt_fixedpoint(x::AbstractArray)
    y = ones(eltype(x), size(x))
    for _ in 1:10
        y .= 0.5 .* (y .+ x ./ y)
    end
    y
end

function forward(x)
    println("forward called")
    sqrt_fixedpoint(x)
end

conditions(x, y) = 0.5 .* (y .+ x ./ y) .- y

implicit = ImplicitFunction(forward, conditions)

ForwardDiff.jacobian(implicit, x)
```
Output:
```
forward called
forward called
forward called
forward called
forward called
forward called
forward called
forward called
forward called

100×100 Matrix{Float64}:
...
```

This behavior is expected, as forward differentiation should return also the value of the function (for which we need to call `forward`) along with the partials. But for chunked evaluations of derivatives, this is redundant and may be a major performance issue if `forward` is expensive.

As a workaround, you could precalculate the solution and short-circuit the forward pass:
```julia
function forward(x; y_solution=nothing)
    if !isnothing(y_solution)
        println("forward called with y_solution, no work required")
        return y_solution
    end
    println("forward called, doing expensive computation")
    sqrt_fixedpoint(x)
end

conditions(x, y; y_solution=nothing) = 0.5 .* (y .+ x ./ y) .- y

implicit = ImplicitFunction(forward, conditions)

y_solution = implicit(x)
ForwardDiff.jacobian(_x -> implicit(_x; y_solution), x)
```

Output:
```
forward called, doing expensive computation
forward called with y_solution, no work required
forward called with y_solution, no work required
forward called with y_solution, no work required
forward called with y_solution, no work required
forward called with y_solution, no work required
forward called with y_solution, no work required
forward called with y_solution, no work required
forward called with y_solution, no work required
forward called with y_solution, no work required

100×100 Matrix{Float64}:
...
```

It seems to me as if there is no sane way of solving this directly in the implementation of `implicit` for dual numbers. You would need to have some caching mechanism for the function value, which goes against the general idea of forward mode autodiff.

Maybe it would be useful to add the workaround to the documentation, the sections "Advanced use cases" or "Tricks" seem to be good places.

**Comment by gdalle** [comment]
I'm not sure I understand, do you mean we can save work by only computing the derivative each time and not the primal output?

**Comment by gdalle** [comment]
Is it related to #84 ?

**Comment by sfalmo** [comment]
> I'm not sure I understand, do you mean we can save work by only computing the derivative each time and not the primal output?

Yes, it is sufficient to calculate the primal value only once, and not for every chunk that ForwardDiff computes in the case of large enough input dimension of the given function. See also the docs of ForwardDiff: [How it works](https://juliadiff.org/ForwardDiff.jl/v0.7/dev/how_it_works.html) and [Configuring chunk size](https://juliadiff.org/ForwardDiff.jl/v0.7/user/advanced.html#Configuring-Chunk-Size-1).

As far as I understand, we want to use implicit differentiation to *avoid* running through the forward mapping $x \rightarrow y(x)$ each time a derivative is required, and instead use the usually much cheaper optimality condition $c(x, y(x)) = 0$. In my present use case, calling `forward` amounts to solving a self-consistent equation iteratively, which usually takes a few seconds, while computing the condition for a given solution is basically instantaneous. My input dimension is quite large (~1000), such that `ForwardDiff.jacobian` with default settings result in about 100 chunks and hence 100 calls to `forward`, of which 99 are redundant.

> Is it related to #84 ?

I think #84 deals with the second step: solving the resulting system of linear equations. Maybe @thorek1 can give more details on that.

By the way, strictly speaking, this issue also applies to `ForwardDiff.gradient`, but for scalar-valued functions of some large input vector one usually uses reverse mode autodiff anyway.

**Comment by gdalle** [comment]
I think the solution might be to define an additional override for chunked evaluation as in https://juliadiff.org/ForwardDiff.jl/release-0.10/user/advanced.html#Configuring-Chunk-Size-1

**Comment by sfalmo** [comment]
I think memoization is the way to go here, as @thorek1 suggested. The workaround in my inital comment was actually just a convoluted way of doing this.

I'm not sure if it is wise to implement the memoization in this package, though. One could construct a memoized version of `forward` in the initialization of [ImplicitFunction](https://github.com/gdalle/ImplicitDifferentiation.jl/blob/74e1a86d793753605836814c719263f6f7d01f01/src/implicit_function.jl#L52). Alternatively, one could memoize all calls to [`implicit`](https://github.com/gdalle/ImplicitDifferentiation.jl/blob/74e1a86d793753605836814c719263f6f7d01f01/src/implicit_function.jl#L69), or keep the memoization only to the [ForwardDiff extension](https://github.com/gdalle/ImplicitDifferentiation.jl/blob/74e1a86d793753605836814c719263f6f7d01f01/ext/ImplicitDifferentiationForwardDiffExt.jl#L33).
But all these methods seem dangerous due to possible limitations of memoization and they also lack flexibility. I also found it quite hard to keep all tests passing after trying out some of the above approaches.

It would probably be better to instruct the user in the documentation to provide a memoized version of forward, e.g. by pointing to [Memoize.jl](https://github.com/JuliaCollections/Memoize.jl) or [Memoization.jl](https://github.com/marius311/Memoization.jl), and to make the implications clear.

I am happy to prepare a pull request in any case.

**Comment by gdalle** [comment]
I agree that it sounds hard to implement in ImplicitDifferentiation.jl so that every user is pleased. A docs PR with pointers to memoization in the FAQ would be welcome!
