### ISSUE TITLE
Switch to LinearSolve

### ISSUE THREAD

**Issue by gdalle** [gdalle/ImplicitDifferentiation.jl#5]
Replace [IterativeSolvers](https://github.com/JuliaLinearAlgebra/IterativeSolvers.jl) with [LinearSolve](https://github.com/SciML/LinearSolve.jl) to give users more choice among linear equation solvers.

**Comment by gdalle** [comment]
I ran into https://github.com/FluxML/Zygote.jl/issues/47 when trying to use LinearSolve with the black box wrapper for unconstrained minimization. Sticking to IterativeSolvers for now

**Comment by tpapp** [comment]
Wasn't this fixed by 7072331549eb4a1e5bcb257c50f3239fcc8e5d7b?

**Comment by gdalle** [comment]
Yes I switched to Krylov.jl in the meantime. Still curious to see if we can use LinearSolve.jl though
