### ISSUE TITLE
Return the output only and not the byproduct

### ISSUE THREAD

**Issue by mohamed82008** [gdalle/ImplicitDifferentiation.jl#55]
I think this line should return y only not both y and z.

https://github.com/gdalle/ImplicitDifferentiation.jl/blob/58fa014e9f88175a0490987439a5c5fcada0b546/src/implicit_function.jl#L41

**Comment by mohamed82008** [comment]
ah good point, I suggest defining 2 methods
```julia
function (f::ImplicitFunction)(x, ::Val{return_byproduct} = Val(false); kwargs...) where {return_byproduct}
  y, z = f.forward(x; kwargs...)
  return return_byproduct ? (y, z) : y
end
```

**Comment by mohamed82008** [comment]
Internally we use `Val(true)`. But by default users get `Val(false)`.

**Comment by gdalle** [comment]
Not a bad idea! Do you think we could solve / alleviate #54 with a similar trick?

**Comment by mohamed82008** [comment]
Possibly but it will complicate the code. I am gonna make a PR for this issue and think about the other one some more.

**Comment by gdalle** [comment]
Is this different from
```julia
function (f::ImplicitFunction)(x, ::Val{true}; kwargs...)
  y, z = f.forward(x; kwargs...)
  return (y, z)
end

function (f::ImplicitFunction)(x, ::Val{false}; kwargs...)
  y, z = f.forward(x; kwargs...)
  return y
end
```

**Comment by mohamed82008** [comment]
The ForwardDiff.Dual method needs to be modified and the pullback needs to consider the cases with a single or 2 outputs.
