### ISSUE TITLE
Jacobian byproduct assumed to be constant in x - incompatible with higher order AD

### ISSUE THREAD

**Issue by mohamed82008** [gdalle/ImplicitDifferentiation.jl#60]
Currently the byproduct `z` is assumed to be a constant in `x`. In optimization, `z` may be used to return a Jacobian approximation for use in the `conditions` function. This is fine as long as we only need the gradient of the optimization solution `y`. If we need higher order derivatives, then we would need to propagate the derivatives back through the byproduct `z` which is currently not possible because we always define the cotangent wrt `z` to be `NoTangent()`. I am not sure if there is a way to handle this correctly except to document it perhaps.

**Comment by gdalle** [comment]
It is already documented in the `ImplicitFunction`. Maybe we add it to the FAQ?

**Comment by gdalle** [comment]
I'm pretty sure this is not fixable. If we want a derivative for `z` then we have to
- either assume that `forward` is differentiable, which negates the purpose of the package
- or write another implicit equation for `z`, which is a recursive nightmare

I vote to stick with this nondifferentiable behavior and make it very explicit in the docs

**Comment by mohamed82008** [comment]
I agree at least until a solid use case comes along, there is no point supporting that super niche use case.
