### ISSUE TITLE
Package benchmarks

### ISSUE THREAD

**Issue by gdalle** [gdalle/ImplicitDifferentiation.jl#63]
https://github.com/JuliaCI/PkgBenchmark.jl

**Comment by mohamed82008** [comment]
We should probably benchmark ForwardDiff, Zygote and FiniteDifference for Jacobians and gradients of implicit functions with and without the implicit function theorem. Additionally, here are some packages we may want to benchmark against in Julia and Python for different problems.

Optimization
- https://github.com/google/jaxopt
- https://github.com/jump-dev/DiffOpt.jl
- https://github.com/cvxgrp/cvxpylayers

Optimal transport
- https://github.com/GiulsLu/OT-gradients

Linear solvers
- https://github.com/SciML/LinearSolve.jl

Nonlinear solvers
- https://github.com/SciML/NonlinearSolve.jl

Factorizations
- ChainRules vs DifferentiableFactorizations
