### ISSUE TITLE
Documentation inconsistency for v0.4.4

### ISSUE THREAD

**Issue by JinraeKim** [gdalle/ImplicitDifferentiation.jl#66]
I was trying to implement my own implicit diff function for the minimization of log-sum-exp function, and I found that the documentation for the stable version is somewhat different from what I actually obtained by running a code.

For example, according to the doc of the stable version (https://gdalle.github.io/ImplicitDifferentiation.jl/stable/examples/4_constrained_optim/), I wrote this code:

```julia
using ImplicitDifferentiation
using Flux
using Convex, ECOS
using ComponentArrays


# x = rand(2) .+ [0, 1]
i_max = 10
m = 2
A = 2 * rand(i_max, m) .- 1
B = 2 * rand(i_max) .- 1
θ = ComponentArray(A=A, B=B)
u_min = -2*ones(m)
u_max = +2*ones(m)


# function mysqrt_cstr_optim(x)
function minimise_logsumexp(θ; T, u_min, u_max, initial_guess, solver=() -> ECOS.Optimizer())
    (; A, B) = θ
    m = size(A)[2]
    u = Convex.Variable(m)
    if initial_guess != nothing
        u.value = initial_guess
    end
    obj = T * Convex.logsumexp((1/T)*(A*u + B))
    prob = Convex.minimize(obj)
    prob.constraints += [u >= u_min]
    prob.constraints += [u <= u_max]
    solve!(prob, solver(), silent_solver=true, verbose=false)
    minimiser = typeof(u.value) <: Number ? [u.value] : u.value[:]  # to make it a vector
    return minimiser
end


function forward_cstr_optim(x; kwargs...)
    # y = mysqrt_cstr_optim(x)
    y = minimise_logsumexp(x; kwargs...)
    # z = 0
    return y
end


# function proj_hypercube(p)
#     return max.(0, min.(1, p))
# end
function proj_hypercube(p; u_min, u_max)
    return max.(u_min, min.(u_max, p))
end

# function conditions_cstr_optim(x, y)
function conditions_cstr_optim(θ, u; kwargs...)
    # ∇₂f = 2 .* (y .^ 2 .- x)
    (; A, B) = θ
    ∇₂f = A' * Flux.softmax(A*u+B)
    η = 0.1
    # return y .- proj_hypercube(y .- η .* ∇₂f)
    return u .- proj_hypercube(u .- η .* ∇₂f; kwargs...)
end


function implicit_cstr_optim_func(θ; T, u_min, u_max, initial_guess, solver)
    tmp = ImplicitFunction(
                           θ -> forward_cstr_optim(θ; T, u_min, u_max, initial_guess, solver),
                           (θ, u) -> conditions_cstr_optim(θ, u; u_min, u_max),
                          )
    tmp(θ)
end

implicit_cstr_optim_func(θ; T=1, u_min=-ones(m), u_max=+ones(m), initial_guess=nothing, solver=() -> ECOS.Optimizer())
```

In docs, when calling the implicit function, it is expected to give an array.
With `v0.5.0-DEV`, the result seems fine:
```
julia> implicit_cstr_optim_func(θ; T=1, u_min=-ones(m), u_max=+ones(m), initial_guess=nothing, solver=() -> ECOS.Optimizer())

2-element Vector{Float64}:
  0.11430458077043977
 -0.9999999846444508
```

However, with `v0.4.4` (the stable version), it gives me a tuple like this:
```
julia> implicit_cstr_optim_func(θ; T=1, u_min=-ones(m), u_max=+ones(m), initial_guess=nothing, solver=() -> ECOS.Optimizer())
(0.710863877230062, -0.932445241056164)
```

**Comment by JinraeKim** [comment]
Also, if there is a plan for v0.5.0 release, please let me know :>

**Comment by mohamed82008** [comment]
On the latest release you would need to return `z` from `forward_cstr_optim` and the implicit function returns both `y` and `z` when called. The following changes should fix it.
```julia
function forward_cstr_optim(x; kwargs...)
  y = minimise_logsumexp(x; kwargs...)
  z = 0
  return y, z
end

function implicit_cstr_optim_func(θ; T, u_min, u_max, initial_guess, solver)
  tmp = ImplicitFunction(
    θ -> forward_cstr_optim(θ; T, u_min, u_max, initial_guess, solver),
    (θ, u) -> conditions_cstr_optim(θ, u; u_min, u_max),
  )
  tmp(θ)[1]
end
```

**Comment by mohamed82008** [comment]
v0.5 will likely be released after https://github.com/gdalle/ImplicitDifferentiation.jl/pull/64 because it might change the API a little for passing in linear solvers. But I won't be able to wrap this PR up for at least week or 2 because I am in a conference now. Then @gdalle needs to find the time to review, merge and release. So hopefully within a month, 0.5 should be out but Guillaume can correct me if I am wrong. Anyways if the above fix works for you, I think this is consistent with the docs and we can close this issue.

**Comment by gdalle** [comment]
> I found that the documentation for the stable version is somewhat different from what I actually obtained by running a code.

Mohamed is right:
- in the stable release 0.4.4, you always have to provide the "additional information" `z`
- in the upcoming version 0.5.0 we make it optional

> So hopefully within a month, 0.5 should be out but Guillaume can correct me if I am wrong.

Sounds about right to me

**Comment by JinraeKim** [comment]
Thank you for your detailed explanation!
