### ISSUE TITLE
Support BFGS-like Jacobian approximations

### ISSUE THREAD

**Issue by gdalle** [gdalle/ImplicitDifferentiation.jl#7]
Inspired by https://arxiv.org/abs/1909.01377 (section 3.1.3)

**Comment by mohamed82008** [comment]
This is solved by the additional output or would you like to add an example?

**Comment by gdalle** [comment]
I definitely would like to add an example, but first we need to stabilize the API

**Comment by gdalle** [comment]
API stabilized by #57 
Example issue in #62
