### ISSUE TITLE
Behavior when the linear solver fails

### ISSUE THREAD

**Issue by gdalle** [gdalle/ImplicitDifferentiation.jl#71]
At the moment we throw an error, can we do better? `NaN`s maybe?

**Comment by thorek1** [comment]
returning a flag (Bool) indicating that the linear solver failed would be more helpful. catching errors with `try/catch` is inefficient/costly

**Comment by thorek1** [comment]
Actually this is making my tests fail in the branch where I try to use the latest ImplicitDifferentiation.jl v0.4.4

**Comment by gdalle** [comment]
> returning a flag (Bool) indicating that the linear solver failed would be more helpful. catching errors with try/catch is inefficient/costly

Yeah but where should we return it? The linear solve happens deeeep inside the call stack, and when you do `Zygote.jacobian(implicit, x)` there is no room to send a flag back to the surface, is there?

**Comment by mohamed82008** [comment]
let's just propagate `NaN`s all the way up

**Comment by thorek1** [comment]
What about adding the flag as the last element of the returned values like they do with the linear solvers (krylov at least)

**Comment by mohamed82008** [comment]
We still have to return something at the end of the correct type. Instead of returning garbage, let's just return a vector of NaNs. This is consistent with `0 / 0` which doesn't throw but returns NaN.

**Comment by thorek1** [comment]
As of now he returns whatever krylov finds (eg least squares solution), which is fine as long as you know it didn't solve. Returning NaNs should be fine as well. I hope it doesn't error before I can catch them.

**Comment by gdalle** [comment]
I don't know how to do this in a type-stable way, unless we promote everything to `Float64`, which is the type of `NaN`

**Comment by mohamed82008** [comment]
`convert(float(T), NaN)` does what you expect

**Comment by gdalle** [comment]
Ok, how about the LU presolve?

**Comment by mohamed82008** [comment]
You can use

```julia
lu(A_static, check = false)
```

Then in `solve`, call `issuccess` on the output of `lu` to find out if the LU succeeded. If it didn't return `NaN`s.

**Comment by gdalle** [comment]
Cool, gonna try that

**Comment by gdalle** [comment]
That's a good point. With a presolve I don't think it changes much but we probably would benefit from putting all partials in a single matrix nonetheless

**Comment by thorek1** [comment]
In my view this is the most pressing issue. When using Turing.jl with ImplicitDifferentiation v0.4.4 the errors trip up the sampler, rendering sampling impossible. There is no way of knowing upfront if A is invertible outside of ImplicitDifferentiation. The best solution in my view is to return NaN.

**Comment by gdalle** [comment]
Gonna give it a try today

**Comment by thorek1** [comment]
tested and works. many thanks

**Comment by gdalle** [comment]
cool! I'm currently doing a sprint on the other issues, hope to get the release out sometime this weekend
