### ISSUE TITLE
Speed up ForwardDiffExt with batched solve

### ISSUE THREAD

**Issue by gdalle** [gdalle/ImplicitDifferentiation.jl#84]
See https://github.com/gdalle/ImplicitDifferentiation.jl/issues/71#issuecomment-1662287726 by @thorek1

**Comment by thorek1** [comment]
here you can see nicely as well why its worth having different conditions_backends. if you go from m input elements to n output elements and m >>n you want to use reverse mode overall but the conditions go both ways in terms of dimensionality. once you go from m to n and once from n to m (solution as input). in that sense, the case with the potentially largest efficiency gain is the one where you diff the condition with respect to the solution (`b`). and if m >> n or vice versa it can make sense to use autodiff the other way compared to what you use on the implicit function. I hope this was clear :)

**Comment by gdalle** [comment]
I'm struggling to make this work because `gmres(A, B)` doesn't work to perform parallel solve when `B` is a matrix. On the other hand, `A \ B` works fine

**Comment by thorek1** [comment]
See the vec and reshape operations in my example.

I also gave it a try but was struggling with the operators. Working with realised matrices is somewhat easier for me...

**Comment by thorek1** [comment]
I tried a bit myself and managed for the direct solver case but the linear operator dimensions are a bit tricky to figure out

**Comment by gdalle** [comment]
This is an internal performance issue that can always be improved in a non breaking way, so I'm putting it on hold to focus on the design for v0.5

**Comment by gdalle** [comment]
Fixed by #135 for the dense Jacobian case, see #129 for the lazy Jacobian case
